spring.application.name=API Monitoring

//DB
# Thông tin k?t n?i Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/API_Monitoring
spring.datasource.username=postgres
spring.datasource.password=123456

# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

google.client-id=${GOOGLE_CLIENT_ID}

# REDIS CONFIGURATION (Caching)
# ===============================
# M?c ??nh k?t n?i t?i Redis ch?y trên máy (Local) ho?c Docker
spring.data.redis.host=localhost
spring.data.redis.port=6379
# N?u Redis có m?t kh?u thì ?i?n vào ?ây, không thì ?? tr?ng
spring.data.redis.password=
# Ki?u Cache s? d?ng là Redis
spring.cache.type=redis
# Th?i gian s?ng m?c ??nh c?a Cache (ví d?: 10 phút)
spring.cache.redis.time-to-live=600000
# Cho phép l?u giá tr? null vào cache (tránh Cache Penetration)
spring.cache.redis.cache-null-values=true

# ===============================
# SECURITY CONFIGURATION
# ===============================
# T?t m?c ??nh c?a Spring Boot ?? t? c?u hình theo JWT
spring.main.allow-bean-definition-overriding=true


spring.aop.proxy-target-class=true

# CLOUDINARY CONFIGURATION
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=
