spring.application.name=API Monitoring

//DB
# Thông tin k?t n?i Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/API_Monitoring
spring.datasource.username=postgres
spring.datasource.password=123456

# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=5b53ba39e2855b21690a59e44cf3c06192436ad806353be89e11a6111d61a2c7
jwt.expiration=86400000

google.client-id=629378167921-j6jvluudq97k1abnsol9hpktib7blmlu.apps.googleusercontent.com